// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Matrix.SynapseInterop.Worker.AppserviceSender.Migrations
{
    [DbContext(typeof(AppserviceDb))]
    [Migration("20190304022659_CreateAppserviceNamespaces")]
    partial class CreateAppserviceNamespaces
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
               .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
               .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
               .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Matrix.SynapseInterop.Database.WorkerModels.Appservice", b =>
            {
                b.Property<string>("Id")
                 .ValueGeneratedOnAdd()
                 .HasColumnName("id");

                b.Property<string>("AppserviceToken")
                 .HasColumnName("as_token");

                b.Property<bool>("Enabled")
                 .HasColumnName("enabled");

                b.Property<string>("HomeserverToken")
                 .HasColumnName("hs_token");

                b.Property<string>("Metadata")
                 .HasColumnName("metadata");

                b.Property<string>("SenderLocalpart")
                 .HasColumnName("sender_localpart");

                b.Property<string>("Url")
                 .HasColumnName("url");

                b.HasKey("Id");

                b.ToTable("appservices");
            });

            modelBuilder.Entity("Matrix.SynapseInterop.Database.WorkerModels.AppserviceNamespace", b =>
            {
                b.Property<string>("Id")
                 .ValueGeneratedOnAdd()
                 .HasColumnName("id");

                b.Property<string>("AppserviceId")
                 .HasColumnName("appservice_id");

                b.Property<bool>("Exclusive")
                 .HasColumnName("exclusive");

                b.Property<string>("Kind")
                 .HasColumnName("kind");

                b.Property<string>("Regex")
                 .HasColumnName("regex");

                b.HasKey("Id");

                b.HasIndex("AppserviceId");

                b.ToTable("appservice_namespaces");
            });

            modelBuilder.Entity("Matrix.SynapseInterop.Database.WorkerModels.AppserviceNamespace", b =>
            {
                b.HasOne("Matrix.SynapseInterop.Database.WorkerModels.Appservice")
                 .WithMany("Namespaces")
                 .HasForeignKey("AppserviceId");
            });
#pragma warning restore 612, 618
        }
    }
}
